# ch 2. huggingface tokenizers

이번 챕터에서는 huggingface에서 제공하는 tokenizers 라이브러리를 이용해서 직접 corpus 데이터 셋을 가지고 subword tokenizer를 학습시켜 보겠습니다.

## 데이터 셋 준비

### 네이버 영화 리뷰 데이터 셋

네이버 영화 리뷰 데이터 셋으로 간단히 학습을 진행해보겠습니다.

In [2]:
import pandas as pd

In [3]:
train_df = pd.read_csv("./data/translation_train.csv")

In [4]:
train_df

,kor,eng
0,"mslee가 부재중이셔서, 당신에게 연락드립니다.","since ms.lee is absence, i contacted you."
1,"아래 내용으로 테스트 호텔 지도화가 되었다고 했고, sso를 이용하여 가입 페이지에...",it says that test hotel mapping has been done ...
2,제인이 방에 들어오면 분위기가 바뀝니다.,the atmosphere changes when jane enters the room.
3,나는 네가 그 채팅 앱을 사용하는 것이 싫어.,i dislike you using that chatting app.
4,창의적인 아이디어를 통해 지역과 함께 발전하는 회사입니다.,it's a company growing with the community thro...
...,...,...
399995,그렇군요. 그런데 그날 오후에 서울 떠나서 다른 날로 일정을 잡을 수가 없습니다.,i see. but i cant schedule another date since ...
399996,그건 나에게 온 편지를 받기 위해서예요.,it is getting the letter which was sent to me.
399997,내 생각에는 silicone volume 값을 측정하는 화면만 있으면 될 것 같아.,"in my opinion, all we need is a screen for mea..."
399998,당신은 나를 충분히 안심 시켜 줬어요.,you relieved me enough.
399999,"전 세계 5,000만 명 이상의 가입자가 이용합니다.",there are over 50 million users worldwide.

### 데이터 셋 전처리

결측치를 제거하고, 특수문자나 한자를 제거해주겠습니다.

In [5]:
train_df.isnull().sum()

kor    0
eng    0
dtype: int64

In [6]:
train_df = train_df.dropna()

In [7]:
import re

# 특수 문자 제거 및 소문자화
def preprocess_text(text: str) -> str:
    text = text.lower()
    # text = re.sub(r"[^ㄱ-힣a-zA-Z0-9!?.,\']", r" ", text)
    text = re.sub(r"[^ㄱ-ㅎㅏ-ㅣ가-힣a-zA-Z!?.,\' ]", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

In [7]:
example = "亞 최고의 영화...!! 단연코 BEST 보는 내내 눈물 ㅠㅠ"
preprocess_text(example)

'최고의 영화...!! 단연코 best 보는 내내 눈물 ㅠㅠ'

In [9]:
from tqdm.notebook import tqdm

tqdm.pandas()
train_df["kor"] = train_df["kor"].progress_apply(lambda x: preprocess_text(x))
train_df["eng"] = train_df["eng"].progress_apply(lambda x: preprocess_text(x))

  0%|          | 0/400000 [00:00<?, ?it/s]

  0%|          | 0/400000 [00:00<?, ?it/s]

In [10]:
train_df

,kor,eng
0,"mslee가 부재중이셔서, 당신에게 연락드립니다.","since ms.lee is absence, i contacted you."
1,"아래 내용으로 테스트 호텔 지도화가 되었다고 했고, sso를 이용하여 가입 페이지에...",it says that test hotel mapping has been done ...
2,제인이 방에 들어오면 분위기가 바뀝니다.,the atmosphere changes when jane enters the room.
3,나는 네가 그 채팅 앱을 사용하는 것이 싫어.,i dislike you using that chatting app.
4,창의적인 아이디어를 통해 지역과 함께 발전하는 회사입니다.,it's a company growing with the community thro...
...,...,...
399995,그렇군요. 그런데 그날 오후에 서울 떠나서 다른 날로 일정을 잡을 수가 없습니다.,i see. but i cant schedule another date since ...
399996,그건 나에게 온 편지를 받기 위해서예요.,it is getting the letter which was sent to me.
399997,내 생각에는 silicone volume 값을 측정하는 화면만 있으면 될 것 같아.,"in my opinion, all we need is a screen for mea..."
399998,당신은 나를 충분히 안심 시켜 줬어요.,you relieved me enough.
399999,"전 세계 ,만 명 이상의 가입자가 이용합니다.",there are over million users worldwide.

## huggingface tokenizers

huggingface는 AI 스타트업으로 오픈 소스 라이브러리로 유명합니다. 특히 NLP 분야에서는 huggingface에서 제공하는 트랜스포머 모델을 사용하는 것이 거의 표준으로 자리잡았습니다. 주요 라이브러리는 아래와 같습니다. 

- transformers: 트랜스포머 기본 모델과 이를 응용한 NLP 모델들을 제공
- tokenizers: subword tokenizer 제공

huggingface의 tokenizers는 subword tokenizer의 구현체입니다. 이를 사용하여 tokenizer를 학습시켜 보겠습니다.

In [10]:
!pip install tokenizers

Requirement already satisfied: tokenizers in /Users/user/miniconda3/lib/python3.10/site-packages (0.15.0)
Requirement already satisfied: huggingface_hub<1.0,>=0.16.4 in /Users/user/miniconda3/lib/python3.10/site-packages (from tokenizers) (0.20.2)
Requirement already satisfied: filelock in /Users/user/miniconda3/lib/python3.10/site-packages (from huggingface_hub<1.0,>=0.16.4->tokenizers) (3.9.0)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/user/miniconda3/lib/python3.10/site-packages (from huggingface_hub<1.0,>=0.16.4->tokenizers) (2023.9.2)
Requirement already satisfied: requests in /Users/user/miniconda3/lib/python3.10/site-packages (from huggingface_hub<1.0,>=0.16.4->tokenizers) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in /Users/user/miniconda3/lib/python3.10/site-packages (from huggingface_hub<1.0,>=0.16.4->tokenizers) (4.64.1)
Requirement already satisfied: pyyaml>=5.1 in /Users/user/miniconda3/lib/python3.10/site-packages (from huggingface_hub<1.0,>=0.16.4->tokenizers) (6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /Users/user/miniconda3/lib/python3.10/site-packages (from huggingface_hub<1.0,>=0.16.4->tokenizers) (4.7.1)
Requirement already satisfied: packaging>=20.9 in /Users/user/miniconda3/lib/python3.10/site-packages (from huggingface_hub<1.0,>=0.16.4->tokenizers) (23.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/user/miniconda3/lib/python3.10/site-packages (from requests->huggingface_hub<1.0,>=0.16.4->tokenizers) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/user/miniconda3/lib/python3.10/site-packages (from requests->huggingface_hub<1.0,>=0.16.4->tokenizers) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/user/miniconda3/lib/python3.10/site-packages (from requests->huggingface_hub<1.0,>=0.16.4->tokenizers) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /Users/user/miniconda3/lib/python3.10/site-packages (from requests->huggingface_hub<1.0,>=0.16.4->tokenizers) (2022.12.7)
DEPRECATION: pytorch-lightning 1.8.3.post1 has a non-standard dependency specifier torch>=1.9.*. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pytorch-lightning or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
DEPRECATION: mecab-python 0.996-ko-0.9.2 has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of mecab-python or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063

### Trainer
WordPiece 기반의 subword tokenizer를 만들어보겠습니다.  먼저 tokenizer를 학습시키기 위한 trainer를 만들어줍니다. 이 때, special tokens를 넣어주어야 하는데, 각 토큰의 의미는 다음과 같습니다.

- [PAD]: padding의 약자로 문장 간에 길이를 맞춰주기 위해 일부러 채워넣은 토큰을 의미합니다.
- [UNK]: unknown의 약자로 인식하지 못한 토큰을 나타냅니다.
- [SOS]: start of sentence의 약자로 문장의 시작을 표시해줍니다.
- [EOS]: end of sentence의 약자로 문장의 끝을 표시해줍니다.

In [11]:
from tokenizers.trainers import WordPieceTrainer

trainer = WordPieceTrainer(
    vocab_size=10000,
    min_frequency=5,
    special_tokens=["[PAD]", "[UNK]", "[SOS]", "[EOS]"]
)

### Tokenizer

이제 tokenizer 객체를 만들어주고 trainer를 이용해서 학습시켜 줍니다.

In [17]:
train_df.iloc[:10]["kor"] + " " + train_df.iloc[:10]["eng"]

0    mslee가 부재중이셔서, 당신에게 연락드립니다. since ms.lee is ab...
1    아래 내용으로 테스트 호텔 지도화가 되었다고 했고, sso를 이용하여 가입 페이지에...
2    제인이 방에 들어오면 분위기가 바뀝니다. the atmosphere changes ...
3    나는 네가 그 채팅 앱을 사용하는 것이 싫어. i dislike you using ...
4    창의적인 아이디어를 통해 지역과 함께 발전하는 회사입니다. it's a compan...
5    제 엔진이 죽어서 시동이 안 걸려요. my motor died, and so it ...
6    가스회사 전화번호 좀 알려주세요. tell me the phone number of...
7    당신 물건은 예정된 스케줄대로 선적될 것입니다. your products will ...
8    주디가 휴가 가서 내가 잠시 이 업무를 맡았어. i'm handling this w...
9    스티커는 겉면 플라스틱 봉지에는 필요 없습니다. no sticker is neede...
dtype: object

In [18]:
from tokenizers import Tokenizer
from tokenizers.models import WordPiece 
from tokenizers.pre_tokenizers import Whitespace

def batch_iterator(df, batch_size=1000):
    for i in range(0, len(df), batch_size):
        batch_df = df.iloc[i:i+batch_size]
        yield batch_df["kor"] + " " + batch_df["eng"]

In [19]:
tokenizer = Tokenizer(WordPiece())
tokenizer.pre_tokenizer = Whitespace()
tokenizer.train_from_iterator(batch_iterator(train_df),  trainer=trainer)

## tokenizer 확인

tokenizer가 잘 학습되었는지 확인해보겠습니다.

### vocab 확인

먼저 tokenizer vocab에 어떤 토큰들이 추가되었는지 살펴보겠습니다.

In [20]:
vocabs = tokenizer.get_vocab()
sorted_vocabs = sorted(vocabs.items(), key=lambda x: x[1])

In [21]:
print(sorted_vocabs)

[('[PAD]', 0), ('[UNK]', 1), ('[SOS]', 2), ('[EOS]', 3), ('!', 4), ("'", 5), (',', 6), ('.', 7), ('?', 8), ('a', 9), ('b', 10), ('c', 11), ('d', 12), ('e', 13), ('f', 14), ('g', 15), ('h', 16), ('i', 17), ('j', 18), ('k', 19), ('l', 20), ('m', 21), ('n', 22), ('o', 23), ('p', 24), ('q', 25), ('r', 26), ('s', 27), ('t', 28), ('u', 29), ('v', 30), ('w', 31), ('x', 32), ('y', 33), ('z', 34), ('ㄷ', 35), ('ㄹ', 36), ('ㅅ', 37), ('ㅆ', 38), ('ㅇ', 39), ('ㅈ', 40), ('ㅏ', 41), ('ㅔ', 42), ('ㅠ', 43), ('ㅡ', 44), ('가', 45), ('각', 46), ('간', 47), ('갇', 48), ('갈', 49), ('갉', 50), ('감', 51), ('갑', 52), ('값', 53), ('갓', 54), ('갔', 55), ('강', 56), ('갖', 57), ('갗', 58), ('같', 59), ('갚', 60), ('갛', 61), ('개', 62), ('객', 63), ('갠', 64), ('갤', 65), ('갭', 66), ('갯', 67), ('갰', 68), ('갱', 69), ('갸', 70), ('걀', 71), ('걔', 72), ('거', 73), ('걱', 74), ('건', 75), ('걷', 76), ('걸', 77), ('검', 78), ('겁', 79), ('것', 80), ('겄', 81), ('겆', 82), ('겉', 83), ('겊', 84), ('게', 85), ('겐', 86), ('겔', 87), ('겜', 88), ('겟', 89), ('겠', 90), ('겡', 91), ('겨', 92), ('격', 93), ('겪', 94), ('견', 95), ('결', 96), ('겸', 97), ('겹', 98), ('겼', 99), ('경', 100), ('곁', 101), ('계', 102), ('곗', 103), ('고', 104), ('곡', 105), ('곤', 106), ('곧', 107), ('골', 108), ('곪', 109), ('곯', 110), ('곰', 111), ('곱', 112), ('곳', 113), ('공', 114), ('곶', 115), ('과', 116), ('곽', 117), ('관', 118), ('괂', 119), ('괄', 120), ('괌', 121), ('괏', 122), ('광', 123), ('괘', 124), ('괜', 125), ('괭', 126), ('괴', 127), ('굉', 128), ('교', 129), ('굣', 130), ('구', 131), ('국', 132), ('군', 133), ('굳', 134), ('굴', 135), ('굵', 136), ('굶', 137), ('굼', 138), ('굽', 139), ('굿', 140), ('궁', 141), ('궂', 142), ('궃', 143), ('궈', 144), ('권', 145), ('궐', 146), ('궜', 147), ('궤', 148), ('귀', 149), ('귄', 150), ('귈', 151), ('귐', 152), ('귑', 153), ('귓', 154), ('규', 155), ('균', 156), ('귤', 157), ('그', 158), ('극', 159), ('근', 160), ('글', 161), ('긁', 162), ('금', 163), ('급', 164), ('긋', 165), ('긍', 166), ('기', 167), ('긴', 168), ('긷', 169), ('길', 170), ('김', 171), ('깁', 172), ('깃', 173), ('깄', 174), ('깅', 175), ('깊', 176), ('까', 177), ('깍', 178), ('깎', 179), ('깐', 180), ('깔', 181), ('깜', 182), ('깝', 183), ('깟', 184), ('깠', 185), ('깡', 186), ('깥', 187), ('깨', 188), ('깬', 189), ('깰', 190), ('깹', 191), ('깻', 192), ('깼', 193), ('깽', 194), ('꺠', 195), ('꺼', 196), ('꺽', 197), ('꺾', 198), ('껀', 199), ('껄', 200), ('껌', 201), ('껍', 202), ('껏', 203), ('껐', 204), ('껑', 205), ('께', 206), ('껫', 207), ('껴', 208), ('꼈', 209), ('꼐', 210), ('꼬', 211), ('꼭', 212), ('꼰', 213), ('꼴', 214), ('꼼', 215), ('꼽', 216), ('꼿', 217), ('꽁', 218), ('꽂', 219), ('꽃', 220), ('꽈', 221), ('꽉', 222), ('꽝', 223), ('꽤', 224), ('꽹', 225), ('꾀', 226), ('꾄', 227), ('꾳', 228), ('꾸', 229), ('꾹', 230), ('꾼', 231), ('꿀', 232), ('꿇', 233), ('꿈', 234), ('꿉', 235), ('꿋', 236), ('꿍', 237), ('꿔', 238), ('꿨', 239), ('꿩', 240), ('꿰', 241), ('뀌', 242), ('뀐', 243), ('뀔', 244), ('뀜', 245), ('뀝', 246), ('끄', 247), ('끈', 248), ('끊', 249), ('끌', 250), ('끓', 251), ('끔', 252), ('끕', 253), ('끗', 254), ('끙', 255), ('끝', 256), ('끼', 257), ('끽', 258), ('낀', 259), ('낄', 260), ('낌', 261), ('낍', 262), ('나', 263), ('낙', 264), ('낚', 265), ('난', 266), ('낟', 267), ('날', 268), ('낡', 269), ('남', 270), ('납', 271), ('낫', 272), ('났', 273), ('낭', 274), ('낮', 275), ('낯', 276), ('낱', 277), ('낳', 278), ('내', 279), ('낵', 280), ('낸', 281), ('낼', 282), ('냄', 283), ('냅', 284), ('냇', 285), ('냈', 286), ('냉', 287), ('냐', 288), ('냑', 289), ('냔', 290), ('냘', 291), ('냥', 292), ('너', 293), ('넉', 294), ('넋', 295), ('넌', 296), ('널', 297), ('넓', 298), ('넘', 299), ('넙', 300), ('넛', 301), ('넜', 302), ('넝', 303), ('넣', 304), ('네', 305), ('넥', 306), ('넨', 307), ('넬', 308), ('넴', 309), ('넷', 310), ('넸', 311), ('녀', 312), ('녁', 313), ('년', 314), ('녈', 315), ('념', 316), ('녔', 317), ('녕', 318), ('녘', 319), ('녜', 320), ('노', 321), ('녹', 322), ('논', 323), ('놀', 324), ('놈', 325), ('놉', 326), ('놋', 327), ('농', 328), ('높', 329), ('놓', 330), ('놔', 331), ('놨', 332), ('뇄', 333), ('뇌', 334), ('뇜', 335), ('뇨', 336), ('뇽', 337), ('누', 338), ('눅', 339), ('눈', 340), ('눌', 341), ('눔', 342), ('눕', 343), ('눗', 344), ('눠', 345), ('눴', 346), ('뉘', 347), ('뉜', 348), ('뉠', 349), ('뉩', 350), ('뉴', 351), ('늄', 352), ('늉', 353), ('느', 354), ('늑', 355), ('는', 356), ('늘', 357), ('늙', 358), ('늠', 359), ('늡', 360), ('능', 361), ('늦', 362), ('늪', 363), ('늬', 364), ('니', 365), ('닉', 366), ('닌', 367), ('닏', 368), ('닐', 369), ('님', 370), ('닙', 371), ('닛', 372), ('닝', 373), ('닢', 374), ('다', 375), ('닥', 376), ('닦', 377), ('단', 378), ('닫', 379), ('달', 380), ('닭', 381), ('닮', 382), ('닳', 383), ('담', 384), ('답', 385), ('닷', 386), ('당', 387), ('닻', 388), ('닼', 389), ('닿', 390), ('대', 391), ('댁', 392), ('댄', 393), ('댈', 394), ('댐', 395), ('댑', 396), ('댓', 397), ('댔', 398), ('댕', 399), ('댜', 400), ('더', 401), ('덕', 402), ('덖', 403), ('던', 404), ('덜', 405), ('덟', 406), ('덤', 407), ('덥', 408), ('덧', 409), ('덩', 410), ('덫', 411), ('덮', 412), ('데', 413), ('덱', 414), ('덴', 415), ('델', 416), ('뎀', 417), ('뎁', 418), ('뎃', 419), ('뎄', 420), ('뎅', 421), ('뎌', 422), ('뎠', 423), ('도', 424), ('독', 425), ('돈', 426), ('돋', 427), ('돌', 428), ('돍', 429), ('돎', 430), ('돔', 431), ('돕', 432), ('돗', 433), ('동', 434), ('돛', 435), ('돤', 436), ('돨', 437), ('돼', 438), ('됀', 439), ('됍', 440), ('됐', 441), ('되', 442), ('된', 443), ('될', 444), ('됨', 445), ('됩', 446), ('됬', 447), ('두', 448), ('둑', 449), ('둔', 450), ('둘', 451), ('둠', 452), ('둡', 453), ('둣', 454), ('둥', 455), ('둬', 456), ('뒀', 457), ('뒤', 458), ('뒨', 459), ('뒷', 460), ('뒹', 461), ('듀', 462), ('듄', 463), ('듈', 464), ('듐', 465), ('드', 466), ('득', 467), ('든', 468), ('듣', 469), ('들', 470), ('듦', 471), ('듬', 472), ('듭', 473), ('듯', 474), ('등', 475), ('디', 476), ('딕', 477), ('딘', 478), ('딛', 479), ('딜', 480), ('딤', 481), ('딥', 482), ('딧', 483), ('딨', 484), ('딩', 485), ('딪', 486), ('딫', 487), ('따', 488), ('딱', 489), ('딴', 490), ('딸', 491), ('땀', 492), ('땁', 493), ('땄', 494), ('땅', 495), ('땋', 496), ('때', 497), ('땐', 498), ('땔', 499), ('땜', 500), ('땠', 501), ('땡', 502), ('떄', 503), ('떠', 504), ('떡', 505), ('떤', 506), ('떨', 507), ('떫', 508), ('떱', 509), ('떳', 510), ('떴', 511), ('떵', 512), ('떻', 513), ('떼', 514), ('뗀', 515), ('뗄', 516), ('뗏', 517), ('뗐', 518), ('뗑', 519), ('또', 520), ('똑', 521), ('똘', 522), ('똠', 523), ('똥', 524), ('똬', 525), ('뚜', 526), ('뚝', 527), ('뚤', 528), ('뚫', 529), ('뚱', 530), ('뛰', 531), ('뛴', 532), ('뛸', 533), ('뜀', 534), ('뜁', 535), ('뜨', 536), ('뜩', 537), ('뜬', 538), ('뜯', 539), ('뜰', 540), ('뜸', 541), ('뜹', 542), ('뜻', 543), ('띄', 544), ('띈', 545), ('띌', 546), ('띔', 547), ('띕', 548), ('띠', 549), ('띡', 550), ('띤', 551), ('띱', 552), ('띵', 553), ('라', 554), ('락', 555), ('란', 556), ('랄', 557), ('람', 558), ('랍', 559), ('랏', 560), ('랐', 561), ('랑', 562), ('랖', 563), ('랗', 564), ('래', 565), ('랙', 566), ('랜', 567), ('랠', 568), ('램', 569), ('랩', 570), ('랫', 571), ('랬', 572), ('랭', 573), ('랴', 574), ('략', 575), ('량', 576), ('러', 577), ('럭', 578), ('런', 579), ('럴', 580), ('럼', 581), ('럽', 582), ('럿', 583), ('렀', 584), ('렁', 585), ('렇', 586), ('레', 587), ('렉', 588), ('렌', 589), ('렐', 590), ('렘', 591), ('렙', 592), ('렛', 593), ('렜', 594), ('렝', 595), ('려', 596), ('력', 597), ('련', 598), ('렬', 599), ('렴', 600), ('렵', 601), ('렷', 602), ('렸', 603), ('령', 604), ('례', 605), ('로', 606), ('록', 607), ('론', 608), ('롣', 609), ('롤', 610), ('롬', 611), ('롭', 612), ('롯', 613), ('롱', 614), ('롹', 615), ('뢰', 616), ('료', 617), ('룟', 618), ('룡', 619), ('루', 620), ('룩', 621), ('룬', 622), ('룰', 623), ('룸', 624), ('룹', 625), ('룻', 626), ('룽', 627), ('뤄', 628), ('뤘', 629), ('뤼', 630), ('류', 631), ('륙', 632), ('륜', 633), ('률', 634), ('륨', 635), ('륫', 636), ('륭', 637), ('르', 638), ('륵', 639), ('른', 640), ('를', 641), ('름', 642), ('릅', 643), ('릇', 644), ('릉', 645), ('릎', 646), ('릐', 647), ('리', 648), ('릭', 649), ('린', 650), ('릴', 651), ('림', 652), ('립', 653), ('릿', 654), ('링', 655), ('마', 656), ('막', 657), ('만', 658), ('많', 659), ('맏', 660), ('말', 661), ('맑', 662), ('맘', 663), ('맙', 664), ('맛', 665), ('망', 666), ('맞', 667), ('맟', 668), ('맡', 669), ('맣', 670), ('매', 671), ('맥', 672), ('맨', 673), ('맬', 674), ('맴', 675), ('맵', 676), ('맷', 677), ('맸', 678), ('맹', 679), ('맺', 680), ('먀', 681), ('먄', 682), ('머', 683), ('먹', 684), ('먼', 685), ('멀', 686), ('멈', 687), ('멉', 688), ('멋', 689), ('멍', 690), ('멎', 691), ('멓', 692), ('메', 693), ('멕', 694), ('멘', 695), ('멜', 696), ('멤', 697), ('멥', 698), ('멧', 699), ('멩', 700), ('며', 701), ('면', 702), ('멸', 703), ('몄', 704), ('명', 705), ('몆', 706), ('몇', 707), ('모', 708), ('목', 709), ('몫', 710), ('몬', 711), ('몰', 712), ('몸', 713), ('몹', 714), ('못', 715), ('몽', 716), ('뫼', 717), ('묘', 718), ('묠', 719), ('무', 720), ('묵', 721), ('묶', 722), ('문', 723), ('묻', 724), ('물', 725), ('묽', 726), ('뭄', 727), ('뭅', 728), ('뭇', 729), ('뭉', 730), ('뭍', 731), ('뭐', 732), ('뭔', 733), ('뭘', 734), ('뭡', 735), ('뭣', 736), ('뮈', 737), ('뮌', 738), ('뮐', 739), ('뮤', 740), ('뮨', 741), ('뮬', 742), ('뮴', 743), ('므', 744), ('믄', 745), ('믈', 746), ('믐', 747), ('미', 748), ('믹', 749), ('민', 750), ('믿', 751), ('밀', 752), ('밈', 753), ('밉', 754), ('밋', 755), ('밌', 756), ('밍', 757), ('및', 758), ('밑', 759), ('바', 760), ('박', 761), ('밖', 762), ('반', 763), ('받', 764), ('발', 765), ('밝', 766), ('밟', 767), ('밤', 768), ('밥', 769), ('밧', 770), ('방', 771), ('밭', 772), ('배', 773), ('백', 774), ('밴', 775), ('밸', 776), ('뱀', 777), ('뱃', 778), ('뱅', 779), ('뱉', 780), ('버', 781), ('벅', 782), ('번', 783), ('벌', 784), ('범', 785), ('법', 786), ('벗', 787), ('벙', 788), ('벚', 789), ('벛', 790), ('베', 791), ('벡', 792), ('벤', 793), ('벨', 794), ('벳', 795), ('벴', 796), ('벵', 797), ('벼', 798), ('벽', 799), ('변', 800), ('별', 801), ('볍', 802), ('볐', 803), ('병', 804), ('볕', 805), ('보', 806), ('복', 807), ('볶', 808), ('본', 809), ('볼', 810), ('봄', 811), ('봅', 812), ('봇', 813), ('봉', 814), ('봐', 815), ('봣', 816), ('봤', 817), ('봬', 818), ('뵀', 819), ('뵈', 820), ('뵌', 821), ('뵐', 822), ('뵙', 823), ('부', 824), ('북', 825), ('분', 826), ('붇', 827), ('불', 828), ('붉', 829), ('붐', 830), ('붑', 831), ('붓', 832), ('붕', 833), ('붙', 834), ('뷔', 835), ('뷰', 836), ('뷴', 837), ('뷸', 838), ('브', 839), ('븐', 840), ('블', 841), ('븕', 842), ('비', 843), ('빅', 844), ('빈', 845), ('빌', 846), ('빔', 847), ('빕', 848), ('빗', 849), ('빙', 850), ('빚', 851), ('빛', 852), ('빠', 853), ('빡', 854), ('빤', 855), ('빨', 856), ('빴', 857), ('빵', 858), ('빻', 859), ('빼', 860), ('빽', 861), ('뺀', 862), ('뺄', 863), ('뺌', 864), ('뺍', 865), ('뺏', 866), ('뺐', 867), ('뺑', 868), ('뺨', 869), ('뺵', 870), ('뻐', 871), ('뻑', 872), ('뻔', 873), ('뻗', 874), ('뻘', 875), ('뻣', 876), ('뻤', 877), ('뻥', 878), ('뻬', 879), ('뼈', 880), ('뼉', 881), ('뼘', 882), ('뼛', 883), ('뽀', 884), ('뽁', 885), ('뽈', 886), ('뽐', 887), ('뽑', 888), ('뽕', 889), ('뾰', 890), ('뿅', 891), ('뿌', 892), ('뿍', 893), ('뿐', 894), ('뿔', 895), ('뿜', 896), ('쁘', 897), ('쁜', 898), ('쁠', 899), ('쁨', 900), ('쁩', 901), ('삐', 902), ('삑', 903), ('삔', 904), ('삘', 905), ('사', 906), ('삭', 907), ('삯', 908), ('산', 909), ('살', 910), ('삶', 911), ('삻', 912), ('삼', 913), ('삽', 914), ('삿', 915), ('샀', 916), ('상', 917), ('샅', 918), ('새', 919), ('색', 920), ('샌', 921), ('샐', 922), ('샘', 923), ('샙', 924), ('샛', 925), ('샜', 926), ('생', 927), ('샤', 928), ('샥', 929), ('샨', 930), ('샬', 931), ('샴', 932), ('샵', 933), ('샷', 934), ('샹', 935), ('샾', 936), ('섀', 937), ('섕', 938), ('서', 939), ('석', 940), ('섞', 941), ('선', 942), ('섣', 943), ('설', 944), ('섬', 945), ('섭', 946), ('섯', 947), ('섰', 948), ('성', 949), ('세', 950), ('섹', 951), ('센', 952), ('셀', 953), ('셈', 954), ('셉', 955), ('셋', 956), ('셌', 957), ('셔', 958), ('션', 959), ('셜', 960), ('셧', 961), ('셨', 962), ('셩', 963), ('셰', 964), ('셸', 965), ('소', 966), ('속', 967), ('손', 968), ('솔', 969), ('솜', 970), ('솝', 971), ('솟', 972), ('송', 973), ('솥', 974), ('솨', 975), ('쇄', 976), ('쇠', 977), ('쇤', 978), ('쇳', 979), ('쇼', 980), ('숀', 981), ('숄', 982), ('숍', 983), ('숏', 984), ('숑', 985), ('숖', 986), ('수', 987), ('숙', 988), ('순', 989), ('숟', 990), ('술', 991), ('숨', 992), ('숩', 993), ('숫', 994), ('숭', 995), ('숯', 996), ('숱', 997), ('숲', 998), ('숴', 999), ('쉈', 1000), ('쉐', 1001), ('쉑', 1002), ('쉘', 1003), ('쉠', 1004), ('쉬', 1005), ('쉰', 1006), ('쉴', 1007), ('쉼', 1008), ('쉽', 1009), ('쉿', 1010), ('슈', 1011), ('슐', 1012), ('슘', 1013), ('슛', 1014), ('슝', 1015), ('스', 1016), ('슥', 1017), ('슨', 1018), ('슬', 1019), ('슭', 1020), ('슴', 1021), ('습', 1022), ('슷', 1023), ('승', 1024), ('시', 1025), ('식', 1026), ('신', 1027), ('싣', 1028), ('실', 1029), ('싫', 1030), ('심', 1031), ('십', 1032), ('싯', 1033), ('싱', 1034), ('싶', 1035), ('싸', 1036), ('싹', 1037), ('싼', 1038), ('쌀', 1039), ('쌈', 1040), ('쌉', 1041), ('쌌', 1042), ('쌍', 1043), ('쌓', 1044), ('쌔', 1045), ('쌤', 1046), ('쌩', 1047), ('쌰', 1048), ('써', 1049), ('썩', 1050), ('썬', 1051), ('썰', 1052), ('썸', 1053), ('썹', 1054), ('썼', 1055), ('썽', 1056), ('쎄', 1057), ('쎈', 1058), ('쏘', 1059), ('쏙', 1060), ('쏜', 1061), ('쏟', 1062), ('쏠', 1063), ('쏨', 1064), ('쏩', 1065), ('쏭', 1066), ('쏴', 1067), ('쐈', 1068), ('쐐', 1069), ('쐬', 1070), ('쐴', 1071), ('쑤', 1072), ('쑥', 1073), ('쑨', 1074), ('쑹', 1075), ('쓰', 1076), ('쓱', 1077), ('쓴', 1078), ('쓸', 1079), ('씀', 1080), ('씁', 1081), ('씌', 1082), ('씨', 1083), ('씩', 1084), ('씬', 1085), ('씰', 1086), ('씸', 1087), ('씹', 1088), ('씻', 1089), ('씽', 1090), ('아', 1091), ('악', 1092), ('안', 1093), ('앉', 1094), ('않', 1095), ('알', 1096), ('앎', 1097), ('앓', 1098), ('암', 1099), ('압', 1100), ('앗', 1101), ('았', 1102), ('앙', 1103), ('앚', 1104), ('앞', 1105), ('애', 1106), ('액', 1107), ('앤', 1108), ('앨', 1109), ('앰', 1110), ('앱', 1111), ('앳', 1112), ('앴', 1113), ('앵', 1114), ('야', 1115), ('약', 1116), ('얀', 1117), ('얄', 1118), ('얇', 1119), ('얌', 1120), ('얍', 1121), ('얏', 1122), ('얐', 1123), ('양', 1124), ('얕', 1125), ('얗', 1126), ('얘', 1127), ('어', 1128), ('억', 1129), ('언', 1130), ('얹', 1131), ('얻', 1132), ('얼', 1133), ('얽', 1134), ('엄', 1135), ('업', 1136), ('없', 1137), ('엇', 1138), ('었', 1139), ('엉', 1140), ('엊', 1141), ('엌', 1142), ('엎', 1143), ('에', 1144), ('엑', 1145), ('엔', 1146), ('엘', 1147), ('엠', 1148), ('엡', 1149), ('엣', 1150), ('엥', 1151), ('여', 1152), ('역', 1153), ('엮', 1154), ('연', 1155), ('열', 1156), ('엷', 1157), ('염', 1158), ('엽', 1159), ('엾', 1160), ('엿', 1161), ('였', 1162), ('영', 1163), ('옅', 1164), ('옆', 1165), ('옇', 1166), ('예', 1167), ('옌', 1168), ('옐', 1169), ('옙', 1170), ('옛', 1171), ('오', 1172), ('옥', 1173), ('온', 1174), ('올', 1175), ('옮', 1176), ('옳', 1177), ('옴', 1178), ('옵', 1179), ('옷', 1180), ('옹', 1181), ('옻', 1182), ('와', 1183), ('왁', 1184), ('완', 1185), ('왈', 1186), ('왐', 1187), ('왑', 1188), ('왓', 1189), ('왔', 1190), ('왕', 1191), ('왜', 1192), ('왠', 1193), ('외', 1194), ('왼', 1195), ('요', 1196), ('욕', 1197), ('욘', 1198), ('욤', 1199), ('욥', 1200), ('욧', 1201), ('용', 1202), ('우', 1203), ('욱', 1204), ('운', 1205), ('울', 1206), ('움', 1207), ('웁', 1208), ('웃', 1209), ('웅', 1210), ('워', 1211), ('웍', 1212), ('원', 1213), ('웓', 1214), ('월', 1215), ('웜', 1216), ('웟', 1217), ('웠', 1218), ('웡', 1219), ('웨', 1220), ('웩', 1221), ('웬', 1222), ('웰', 1223), ('웸', 1224), ('웹', 1225), ('웽', 1226), ('위', 1227), ('윅', 1228), ('윈', 1229), ('윌', 1230), ('윔', 1231), ('윕', 1232), ('윗', 1233), ('윙', 1234), ('유', 1235), ('육', 1236), ('윤', 1237), ('율', 1238), ('윳', 1239), ('융', 1240), ('윷', 1241), ('으', 1242), ('윽', 1243), ('은', 1244), ('을', 1245), ('읊', 1246), ('음', 1247), ('읍', 1248), ('응', 1249), ('의', 1250), ('읩', 1251), ('이', 1252), ('익', 1253), ('인', 1254), ('읹', 1255), ('일', 1256), ('읽', 1257), ('잃', 1258), ('임', 1259), ('입', 1260), ('잇', 1261), ('있', 1262), ('잉', 1263), ('잊', 1264), ('잌', 1265), ('잎', 1266), ('자', 1267), ('작', 1268), ('잔', 1269), ('잖', 1270), ('잘', 1271), ('잠', 1272), ('잡', 1273), ('잣', 1274), ('잤', 1275), ('장', 1276), ('잦', 1277), ('재', 1278), ('잭', 1279), ('잰', 1280), ('잴', 1281), ('잼', 1282), ('잽', 1283), ('잿', 1284), ('쟀', 1285), ('쟁', 1286), ('쟈', 1287), ('쟤', 1288), ('쟨', 1289), ('저', 1290), ('적', 1291), ('전', 1292), ('절', 1293), ('젊', 1294), ('점', 1295), ('접', 1296), ('젓', 1297), ('젔', 1298), ('정', 1299), ('젖', 1300), ('제', 1301), ('젝', 1302), ('젠', 1303), ('젤', 1304), ('젬', 1305), ('젯', 1306), ('져', 1307), ('젹', 1308), ('젼', 1309), ('졌', 1310), ('졍', 1311), ('조', 1312), ('족', 1313), ('존', 1314), ('졸', 1315), ('좀', 1316), ('좁', 1317), ('종', 1318), ('좆', 1319), ('좇', 1320), ('좋', 1321), ('좌', 1322), ('죄', 1323), ('죗', 1324), ('죠', 1325), ('죤', 1326), ('주', 1327), ('죽', 1328), ('준', 1329), ('줄', 1330), ('줌', 1331), ('줍', 1332), ('줏', 1333), ('중', 1334), ('줒', 1335), ('줘', 1336), ('줬', 1337), ('쥐', 1338), ('쥔', 1339), ('쥘', 1340), ('쥠', 1341), ('쥬', 1342), ('쥰', 1343), ('쥴', 1344), ('즈', 1345), ('즉', 1346), ('즌', 1347), ('즐', 1348), ('즘', 1349), ('즙', 1350), ('증', 1351), ('지', 1352), ('직', 1353), ('진', 1354), ('짇', 1355), ('질', 1356), ('짊', 1357), ('짐', 1358), ('집', 1359), ('짓', 1360), ('징', 1361), ('짖', 1362), ('짙', 1363), ('짚', 1364), ('짜', 1365), ('짝', 1366), ('짠', 1367), ('짢', 1368), ('짤', 1369), ('짦', 1370), ('짧', 1371), ('짬', 1372), ('짭', 1373), ('짰', 1374), ('짱', 1375), ('째', 1376), ('짹', 1377), ('짼', 1378), ('쨀', 1379), ('쨈', 1380), ('쨋', 1381), ('쨌', 1382), ('쨍', 1383), ('쩌', 1384), ('쩍', 1385), ('쩐', 1386), ('쩔', 1387), ('쩜', 1388), ('쩝', 1389), ('쩡', 1390), ('쪄', 1391), ('쪘', 1392), ('쪼', 1393), ('쪽', 1394), ('쫀', 1395), ('쫄', 1396), ('쫌', 1397), ('쫑', 1398), ('쫒', 1399), ('쫓', 1400), ('쫙', 1401), ('쬐', 1402), ('쬔', 1403), ('쭈', 1404), ('쭉', 1405), ('쭐', 1406), ('쭙', 1407), ('쭤', 1408), ('쮸', 1409), ('쯔', 1410), ('쯤', 1411), ('쯩', 1412), ('찌', 1413), ('찍', 1414), ('찎', 1415), ('찐', 1416), ('찔', 1417), ('찜', 1418), ('찝', 1419), ('찡', 1420), ('찢', 1421), ('찧', 1422), ('차', 1423), ('착', 1424), ('찬', 1425), ('찮', 1426), ('찰', 1427), ('참', 1428), ('찹', 1429), ('찻', 1430), ('찼', 1431), ('창', 1432), ('찾', 1433), ('찿', 1434), ('챃', 1435), ('채', 1436), ('책', 1437), ('챈', 1438), ('챌', 1439), ('챔', 1440), ('챕', 1441), ('챗', 1442), ('챘', 1443), ('챙', 1444), ('챠', 1445), ('챤', 1446), ('챦', 1447), ('챱', 1448), ('처', 1449), ('척', 1450), ('천', 1451), ('철', 1452), ('첨', 1453), ('첩', 1454), ('첫', 1455), ('청', 1456), ('체', 1457), ('첵', 1458), ('첸', 1459), ('첼', 1460), ('쳐', 1461), ('쳡', 1462), ('쳤', 1463), ('쳥', 1464), ('초', 1465), ('촉', 1466), ('촌', 1467), ('촐', 1468), ('촘', 1469), ('촙', 1470), ('촛', 1471), ('총', 1472), ('촨', 1473), ('촬', 1474), ('최', 1475), ('쵸', 1476), ('추', 1477), ('축', 1478), ('춘', 1479), ('출', 1480), ('춤', 1481), ('춥', 1482), ('춧', 1483), ('충', 1484), ('춰', 1485), ('췄', 1486), ('췌', 1487), ('취', 1488), ('츄', 1489), ('츈', 1490), ('츌', 1491), ('츠', 1492), ('측', 1493), ('츨', 1494), ('츰', 1495), ('층', 1496), ('치', 1497), ('칙', 1498), ('친', 1499), ('칟', 1500), ('칠', 1501), ('칡', 1502), ('침', 1503), ('칩', 1504), ('칫', 1505), ('칭', 1506), ('카', 1507), ('칵', 1508), ('칸', 1509), ('칼', 1510), ('캄', 1511), ('캅', 1512), ('캇', 1513), ('캉', 1514), ('캐', 1515), ('캔', 1516), ('캘', 1517), ('캠', 1518), ('캡', 1519), ('캣', 1520), ('캥', 1521), ('캬', 1522), ('커', 1523), ('컥', 1524), ('컨', 1525), ('컫', 1526), ('컬', 1527), ('컴', 1528), ('컵', 1529), ('컷', 1530), ('컸', 1531), ('컹', 1532), ('케', 1533), ('켄', 1534), ('켈', 1535), ('켐', 1536), ('켑', 1537), ('켓', 1538), ('켜', 1539), ('켠', 1540), ('켤', 1541), ('켬', 1542), ('켭', 1543), ('켰', 1544), ('코', 1545), ('콕', 1546), ('콘', 1547), ('콜', 1548), ('콤', 1549), ('콥', 1550), ('콧', 1551), ('콩', 1552), ('콰', 1553), ('콸', 1554), ('쾃', 1555), ('쾅', 1556), ('쾌', 1557), ('쾨', 1558), ('쾰', 1559), ('쿄', 1560), ('쿠', 1561), ('쿡', 1562), ('쿤', 1563), ('쿨', 1564), ('쿰', 1565), ('쿱', 1566), ('쿵', 1567), ('쿼', 1568), ('퀀', 1569), ('퀄', 1570), ('퀏', 1571), ('퀘', 1572), ('퀜', 1573), ('퀴', 1574), ('퀵', 1575), ('퀸', 1576), ('퀼', 1577), ('큐', 1578), ('큘', 1579), ('큠', 1580), ('크', 1581), ('큰', 1582), ('클', 1583), ('큼', 1584), ('큽', 1585), ('키', 1586), ('킥', 1587), ('킨', 1588), ('킬', 1589), ('킴', 1590), ('킵', 1591), ('킷', 1592), ('킹', 1593), ('타', 1594), ('탁', 1595), ('탄', 1596), ('탈', 1597), ('탉', 1598), ('탐', 1599), ('탑', 1600), ('탓', 1601), ('탔', 1602), ('탕', 1603), ('태', 1604), ('택', 1605), ('탠', 1606), ('탤', 1607), ('탬', 1608), ('탭', 1609), ('탯', 1610), ('탰', 1611), ('탱', 1612), ('터', 1613), ('턱', 1614), ('턴', 1615), ('털', 1616), ('텀', 1617), ('텁', 1618), ('텃', 1619), ('텄', 1620), ('텅', 1621), ('테', 1

4000 ~ 5000개까지는 초기 기본 토큰들로 채워져 있고, 그 뒤로는 함께 자주 등장하는 글자끼리 묶인 토큰들을 확인할 수 있습니다. 앞에 ##이 붙은 토큰들은 단어의 시작 지점이 아닌 위치에 등장하는 토큰들입니다.

### 샘플 토큰화

예시 문장들을 토큰화 해보겠습니다.

In [16]:
samples = [
    "너무 재밌어요, 꿀잼 인정!",
    "보다가 중간에 졸았습니다 ㅠㅠ 비추에요"
]

In [17]:
for sample in samples:
    output = tokenizer.encode(sample)
    print(output.ids)
    print(output.tokens)

[4882, 5396, 6, 6020, 6309, 4]
['너무', '재밌어요', ',', '꿀잼', '인정', '!']
[5285, 5836, 1843, 6944, 5035, 6208, 5377]
['보다가', '중간에', '졸', '##았습니다', 'ㅠㅠ', '비추', '##에요']

### 저장

잘 학습된 것을 확인했다면 파일에 저장하겠습니다.

In [22]:
tokenizer.save("./data/translation_tokenizer.json")

## 정리

이번 챕터에서는 huggingface에서 제공하는 tokenizers 라이브러리를 이용해서 직접 subword tokenizer를 만들어보았습니다. subword tokenizer는 활용도가 매우 높으니, 사용법을 잘 기억해주시기 바랍니다.